#!/bin/sh
gitleaks git --staged --redact -v --no-banner || exit 1

# Run local hook if it exists
LOCAL_HOOK="$(git rev-parse --git-dir)/hooks/pre-commit"
[ -x "$LOCAL_HOOK" ] && exec "$LOCAL_HOOK"
exit 0
